spring:
  application:
    name: member-service
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/my_database?useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: root_password
    hikari:
      connection-timeout: 20000
      maximum-pool-size: 10
      minimum-idle: 5

  data:
    redis:
      host: 127.0.0.1
      port: 6379
      timeout: 2000ms

server:
  port: 8080

